apiVersion: v1
data:
  password: Y1k1YW82SnoycU1WMERMOQ==
kind: Secret
metadata:
  creationTimestamp: "2024-07-19T03:41:18Z"
  name: argocd-initial-admin-secret
  namespace: argocd
  resourceVersion: "811034"
  uid: 0736ddc9-1ea0-4171-b7a9-8a7513702df2
type: Opaque
